### ISSUE TITLE
Week 314 Feedback 

### ISSUE THREAD

**Issue by andrew-bortvin** [dtaylo95/qbb2023-answers#1]
Completed `README.md`

**10/10**

| Exercise | Points Possible | Grade |
| -------- | ------- | ------- |
| Spelled your name correctly | 10 |  10  | 

Great work!

**Comment by dtaylo95** [comment]
Hey Andrew, I fixed this.

**Comment by andrew-bortvin** [comment]
Regarded!

**Comment by andrew-bortvin** [comment]
regraded!
